= PDOK JSON
Raymond Kroon <raymond.kroon@kadaster.nl>, Bas Duineveld <bas.duineveld@kadaster.nl>
v2.0 2017-08-11

De PDOK JSON aanleverstandaard. Om aanleveringen te stroomlijnen.

Aanlevering is gebaseerd op het volgende:

* Basis van alles is een *feature*: de attributen van een object gecombineerd met velden die de mutatieactie
beschrijven.
* Een *collection* is een verzameling features van hetzelfde objecttype (bijv. pand).
Over het algemeen zullen features van één collection dezelfde attribuutnamen hebben, maar hier zitten vooralsnog geen
beperkingen op.
* In de ideale situatie hebben features precies één geometrie en platte attributen.
Nul of meerdere geometrieën en complexe attributen worden ondersteund, maar leiden zoals hieronder beschreven mogelijk
tot ander gedrag.
* Van features wordt historie bijgehouden (in het geval van wijzigingen).

IMPORTANT: collection-namen en attribuutnamen zijn hoofdlettergevoelig, maar gebruik van twee collection-namen die zich
enkel in hoofdlettergebruik onderscheiden, is momenteel nog niet mogelijk.

== Aanlevering
De aanlevering geschiedt in 1 bestand:

[source, json, subs="macros"]
----
{
    "_meta": {
        // Header met metadata. Voor toekomstig gebruik, momenteel niet gevuld.
    },
    "dataset": "dataset-identifier",
    "features" : pass:quotes[[ _feature objects_ ]]
}
----

IMPORTANT: De volgorde is hier belangrijk! Features moet het laatste attribuut zijn.

== Features
Features hebben een aantal verplichte velden, die herkenbaar zijn aan de voorloop-underscore (_):

.Verplichte velden
[horizontal]
_action:: new, change, close, delete
_id:: uniek in _collection, string
_collection:: string
_validity:: date-time-string, tijdstip begin geldigheid: __yyyy-MM-dd**T**HH:mm:ss.SSSZ__

Daarnaast zijn er vrije velden (attributen).
Dit mogen simple types (_string, numeriek, boolean_) zijn, complex types (arrays of subobjecten), geometrieobjecten (in een van de ondersteunde formaten, zie verderop) of voorgedefinieerde functies.
Het type wordt bepaald op basis van het eerste voorkomen van een attribuut.

=== Functies
Een functie kan gebruikt worden als een attribuut omgezet dient te worden naar een ander type dan string, numeriek of boolean.
Het zijn dus in feite voorgedefinieerde types.
Functies worden als volgt aangeroepen:
[source, json]
----
["~#functienaam", [param1, param2, ...]]
----

Op dit moment zijn de volgende functies beschikbaar:

.Beschikbare functies
[horizontal]
~#moment:: date-time-string (__yyyy-MM-dd**T**HH:mm:ss.SSSZ__) -> DateTime
~#date:: date-string (__yyyy-MM-dd__) -> LocalDate
~#int:: Integer
~#boolean:: Boolean
~#double:: Double
~#geometry:: geometrieobject (zie verderop)

De functies __~#int__, __~#boolean__ en __~#double__ zijn er als alternatief voor de automatische detectie van het attribuuttype.
Ze komen vooral van pas als voor een bepaald attribuut lege (null) waardes kunnen voorkomen, omdat het type dan niet automatisch bepaald kan worden.
In het laatste geval kiest de automatische detectie voor string als er geen functie gebruikt wordt.

Voorbeeld:
[source, json]
----
{
    "getalEen": 15, // Integer
    "getalTwee": null, // String
    "getalDrie": ["~#int", null] // Integer
}
----

=== Geometrieën
Voor geometrieën worden de formaten GML en WKT ondersteund.
Mogelijk wordt in de toekomst ondersteuning voor GeoJSON toegevoegd.

Dat het bij een attribuut om een geometrie gaat, kan op twee manieren aangegeven worden.
Heet het attribuut ___geometry__, dan wordt dit automatisch als geometrie geïnterpreteerd.
Heet het attribuut anders, dan dient bovengenoemde functie __~#geometry__ gebruikt te worden.

Voorbeelden:
[source, json]
----
"_geometry":{
    "type": "gml",
    "gml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
            <gml:Point xmlns:gml=\"http://www.opengis.net/gml\" srsName=\"urn:ogc:def:crs:EPSG::28992\">
                <gml:pos srsDimension=\"2\">154676.328 464046.743</gml:pos>
            </gml:Point>"
},
"andereGeometrie": ["~#geometry", {
    "type": "wkt",
    "wkt": "LINESTRING (154676.328 464046.743, 154676.578 464046.743, 154674.285 464048.372)",
    "srid": 28992
}]
----

Het veld __srid__ is optioneel.
Als het wordt weggelaten, wordt 28992 (Amersfoort / RD New) gebruikt.

=== _action: "new"

[source, json]
----
{
    "_action": "new",
    "_id": "abc",
    "_collection": "voorbeeld_verzameling",
    "_validity": "2010-01-01T00:00:00.000",
    "_geometry": { "type": "gml",
               "gml": "<gml:Point srsName=\"urn:ogc:def:crs:EPSG::28992\"><gml:pos>000150.000 000380.000</gml:pos></gml:Point>"
               },
    "een_datum_veld": ["~#moment", ["2012-04-23T18:25:43.511"]],
    "vrij_veld_1": "ik ben een punt",
    "vrij_veld_2":  "ik ben een lijn",
      .
      .
      .

}
----

=== _action: "change"
Aanvullend verplicht veld bij een _change_ is *_current_validity* Deze timestring moet gelijk zijn aan de huidige ___validity__.

NOTE: Een change aanbieden sluit de huidige periode en start een nieuwe.

*Alleen meegeleverde velden worden gewijzigd*

[source, json]
----
{
    "_action": "update",
    "_id": "abc",
    "_collection": "voorbeeld_verzameling",
    "_validity": "2011-01-01T00:00:00.000",
    "_current_validity": "2010-01-01T00:00:00.000",
    "vrij_veld_1": "Ik ben een Point",
    "vrij_veld_2": null , # <1>
     .
     .
     .

}
----

<1> Als je een veld wilt verwijderen, kun je hem op __null__ zetten.

=== _action: "close"
_validity zorgt ervoor dat we kunnen prikken in het verleden. Daarom is er *close* om de feature af te sluiten.

[source, json]
----
{
    "_action": "close",
    "_id": "abc",
    "_collection": "voorbeeld_verzameling",
    "_validity": "2012-01-01T00:00:00.000", # <1>
    "_current_validity": "2011-01-01T00:00:00.000"
}
----

<1> Dit is de "sluitingsdatum"

IMPORTANT: Na een close kan een object niet meer gemuteerd worden.

=== _action: "delete"
Als er een fout gemaakt is in het verleden, kan hiermee de feature gereset worden, zodat alles weer opnieuw aangeboden kan worden.

[source, json]
----
{
    "_action": "delete",
    "_id": "abc",
    "_collection": "voorbeeld_verzameling",
    "_current_validity": "2012-01-01T00:00:00.000"
}
----

== Feature zonder _geometry
Een feature zonder geometry wordt ook verwerkt. De data kan dan echter niet gevisualiseerd worden. Wel kan het gebruikt worden voor eventuele extracten. Voor de rest is een feature zonder geometry hetzelfde als een feature met geometry.

== Feature-historie
Gebruik makend van het *_validity*-attribuut kan er een historie bijgehouden worden. Hierdoor kunnen we "prikken" in het verleden.

* Een feature is geldig vanaf de validity-datum bij het aanmaken (__new__). Dit is _"versie 1"_.
* Bij een change wordt versie 1 afgesloten en gaat de nieuwe versie in, oftewel _"versie 2"_.
* Dit kan een aantal keer doorgaan, elke keer resulterend in een afgesloten huidige en geopende nieuwe versie.
* Als laatste kan een feature gesloten (*close*) worden. Hierna is een feature niet meer beschikbaar.

[source, json]
----
{
    "_action": "new",
    "_id": "feature1",
    "_collection": "historie-voorbeeld",
    "_validity": "[t1]"
    "value": "foo"
}

{
    "_action": "change",
    "_id": "feature1",
    "_collection": "historie-voorbeeld",
    "_current_validity": "[t1]",
    "_validity": "[t2]"
    "value": "bar"
}

{
    "_action": "change",
    "_id": "feature1",
    "_collection": "historie-voorbeeld",
    "_current_validity": "[t2]",
    "_validity": "[t3]"
    "value": "baz"
}

{
    "_action": "close",
    "_id": "feature1",
    "_collection": "historie-voorbeeld",
    "_current_validity": "[t3]",
    "_validity": "[t4]"
}
----

Dit resulteert in de volgende historie:

----
    t1           t2               t3           t4
-----|------------|----------------|------------|-------------->
 X     value=foo      value=bar       value=baz       X
----
